#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Mar  5 08:59:17 2019

@author: Sergey Vinogradov
"""

import os,csv
import numpy as np
from datetime import datetime
#from datetime import timedelta
import csdlpy

#==============================================================================
def readStation (csvFile, verbose=1):
    """
    Reads one station data from csvFile
    Returns 
    """
    if verbose:
        print '[info]: Reading ' + csvFile
    if not os.path.exists (csvFile):
        print '[error]: File ' + csvFile + ' is not found. Exiting.'
        return

    missingVal = 9999.
    dtime    = []
    tide     = []
    surge    = []
    bias     = []
    twl      = []
    with open( csvFile ) as csvfile:
        data = csv.reader(csvfile, delimiter=',')
        next(data, None)

        for row in data:
            row = [np.nan if float(x) == missingVal else x for x in row]
            TIME, TIDE, OB, SURGE, BIAS, TWL = row
            if TWL is np.nan:
                pass
            else:
                dtime.append   ( datetime.strptime(TIME,'%Y%m%d%H%M') )
                tide.append    ( float (TIDE) )
                surge.append   ( float(SURGE) )
                bias.append    ( float(BIAS) )
                twl.append     ( float(TWL) )
    
    return  {'time'      : dtime, 
             'htp'       : tide,
             'swl'       : surge,
             'cwl'       : twl,
             'bias'      : bias}        

#==============================================================================    
if __name__ == "__main__":

    csvFile = '/Users/svinogra/mirrors/wcoss/surge/gpfs/hps/nco/ops/com/etss/prod/etss.20190305/8518750.csv'
    station = readStation(csvFile)
    print station['cwl']
    
    